---
title: "Instructional Module"
author: "Maribel O. Espiritu & Teofilo F. Mendejar Jr."
format: html
editor: visual
---

### **I. UNIT TITLE/CHAPTER TITLE:**

$\qquad$ Module 1: Quadratic Equations and Inequalities

### **II. LESSON TITLE:**

$\qquad$ Lesson 2D. Solving Quadratic Equations Using the Quadratic Formula

### **III. LESSON OVERVIEW:**

$\qquad$ This module by assessing your knowledge of the different mathematics concepts previously studied and your skills in performing mathematical operations. These knowledge and skills will help you understand solving quadratic equations using the quadratic formula. As you go through this lesson, think of this important question: “How does finding solutions of quadratic equations facilitate solving real-life problems and making decisions?” To find the answer, perform each activity. If you recall the previous lessons, the methods are just applicable for a specific quadratic equation. For example, the process of “factoring” is appropriate only if the quadratic expression is factorable. But do not worry because there is one process that is applicable for all forms of quadratic equations that will be tackled in this module. It is all about solving quadratic equations using quadratic formula.

### **IV. DESIRED LEARNING OUTCOMES**

$\qquad$ At the end of this chapter, the student should be able to:

a.  Solve quadratic equations using quadratic formula. **(M9AL-Ib-2.3)**

### **V. LESSON CONTENT**

$\qquad$ We begin our study of quadratic equations with a look at the concepts of simplifying radicals. Take note that a simplified radical has none of the factors of radicand can be written as powers greater than or equal to the index, there are no fractions under the radical sign and no radicals in the denominator.

$\qquad$ Study how the given radical expressions are simplified.

a. $$
\begin{aligned}
4 + \sqrt{500} &= 4 + \sqrt{(100)(5)}  && \text{Factor out 500 such that one number is the greatest possible perfect square factor.} \\
& = 4 + 10\sqrt{5} && \text{Simplify the radical part and combine terms, whenever possible.}
\end{aligned}
$$

b. $$
\begin{aligned}
\dfrac{-6-\sqrt{12}}{4} &= \dfrac{-6-\sqrt{(4)(3)}}{4}  && \text{Factor out 12 such that one number is the possible perfect square factor} \\
& =  \dfrac{-6-2\sqrt{3}}{4}&& \text{Simplify the radical part} \\
& =  \dfrac{2(-3-\sqrt{3})}{4}&& \text{Factor out the common monomial factor of the numerator, then simplify} \\
& =  \dfrac{-3-\sqrt{3}}{2}
\end{aligned}
$$